api:
  name: "MCP Gateway API"
  version: "1.0"

database:
  type: postgres
  connection:
    # If using the bundled postgres service, set POSTGRES_HOST=mcp-postgres
    # If using your own postgres server outside Docker, set POSTGRES_HOST to your server's address
    hosts:
      - ${POSTGRES_HOST:-localhost}
    user: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-password}
    database: ${POSTGRES_DB:-mydb}
    port: ${POSTGRES_PORT:-5432}
  
  # Add your tables and endpoints configuration here as needed
  # This is a minimal configuration to get the service running
